version: '3.9'

x-swfs-master:
  &swfs-master-common
  image: ${IMAGE_NAME}:${IMAGE_TAG}
  networks:
    seaweedfs-net:
    traefik-net:
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      delay: ${MASTER_RESTART_DELAY:-1s}
    update_config:
      delay: ${MASTER_UPDATE_DELAY:-1m}
    resources:
      limits:
        cpus: '${MASTER_RESOURCES_LIMITS_CPUS:-0.1}'
        memory: ${MASTER_RESOURCES_LIMITS_MEMORY:-64M}
      reservations:
        cpus: '${MASTER_RESOURCES_RESERVATIONS_CPUS:-0.001}'
        memory: ${MASTER_RESOURCES_RESERVATIONS_MEMORY:-16M}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.swfs-master.entrypoints: ${TRAEFIK_ENTRYPOINT}
      traefik.http.routers.swfs-master.rule: Host(`${MASTER_TRAEFIK_SUBDOMAIN:-swfs-master}.${PUBLIC_HOSTNAME}`)
      traefik.http.services.swfs-master.loadbalancer.server.port: 1${MASTER_PORT}
      traefik.http.services.swfs-master.loadbalancer.sticky.cookie: 'true'

services:
  swfs-master-1:
    << : *swfs-master-common
    command: master -ip=${MASTER_HOST}-1 -ip.bind=0.0.0.0 -defaultReplication=${DEFAULT_REPLICATION} -peers=${MASTER_HOST}-1:${MASTER_PORT},${MASTER_HOST}-2:${MASTER_PORT},${MASTER_HOST}-3:${MASTER_PORT}
    volumes:
      - master-1-vol:/data

  swfs-master-2:
    << : *swfs-master-common
    command: master -ip=${MASTER_HOST}-2 -ip.bind=0.0.0.0 -defaultReplication=${DEFAULT_REPLICATION} -peers=${MASTER_HOST}-1:${MASTER_PORT},${MASTER_HOST}-2:${MASTER_PORT},${MASTER_HOST}-3:${MASTER_PORT}
    volumes:
      - master-2-vol:/data

  swfs-master-3:
    << : *swfs-master-common
    command: master -ip=${MASTER_HOST}-3 -ip.bind=0.0.0.0 -defaultReplication=${DEFAULT_REPLICATION} -peers=${MASTER_HOST}-1:${MASTER_PORT},${MASTER_HOST}-2:${MASTER_PORT},${MASTER_HOST}-3:${MASTER_PORT}
    volumes:
      - master-3-vol:/data

  swfs-volume:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    command: volume -ip.bind=0.0.0.0 -max=${VOLUME_MAX:-6} -mserver=${MASTER_HOST}-1:${MASTER_PORT},${MASTER_HOST}-2:${MASTER_PORT},${MASTER_HOST}-3:${MASTER_PORT}
    networks:
      seaweedfs-net:
      traefik-net:
    volumes:
      - volume-vol:/data
    deploy:
      mode: replicated
      replicas: ${VOLUME_REPLICAS:-3}
      restart_policy:
        delay: ${VOLUME_RESTART_DELAY:-5s}
      update_config:
        delay: ${VOLUME_UPDATE_DELAY:-5m}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '${VOLUME_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${VOLUME_RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${VOLUME_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${VOLUME_RESOURCES_RESERVATIONS_MEMORY:-16M}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.swfs-volume.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.swfs-volume.rule: Host(`${VOLUME_TRAEFIK_SUBDOMAIN:-swfs-volume}.${PUBLIC_HOSTNAME}`)
        traefik.http.services.swfs-volume.loadbalancer.server.port: 1${VOLUME_PORT}
        traefik.http.services.swfs-volume.loadbalancer.sticky.cookie: 'true'

  swfs-filer:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    command: filer -ip.bind=0.0.0.0 -master=${MASTER_HOST}-1:${MASTER_PORT},${MASTER_HOST}-2:${MASTER_PORT},${MASTER_HOST}-3:${MASTER_PORT}
    networks:
      seaweedfs-net:
      traefik-net:
    volumes:
      - filer-vol:/data
    deploy:
      mode: global
      restart_policy:
        delay: ${FILER_RESTART_DELAY:-5s}
      update_config:
        delay: ${FILER_UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${FILER_RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${FILER_RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${FILER_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${FILER_RESOURCES_RESERVATIONS_MEMORY:-16M}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.swfs-filer.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.swfs-filer.rule: Host(`${FILER_TRAEFIK_SUBDOMAIN:-swfs-filer}.${PUBLIC_HOSTNAME}`)
        traefik.http.services.swfs-filer.loadbalancer.server.port: 1${FILER_PORT}
        traefik.http.services.swfs-filer.loadbalancer.sticky.cookie: 'true'

networks:
  seaweedfs-net:
    name: ${SEAWEEDFS_NET_NAME:-seaweedfs-net}
    driver: ${SEAWEEDFS_NET_DRIVER:-overlay}
    attachable: ${SEAWEEDFS_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  master-1-vol:
    name: ${MASTER_1_VOL_NAME:-seaweedfs-master-1}

  master-2-vol:
    name: ${MASTER_2_VOL_NAME:-seaweedfs-master-2}

  master-3-vol:
    name: ${MASTER_3_VOL_NAME:-seaweedfs-master-3}

  volume-vol:
    name: ${VOLUME_VOL_NAME:-seaweedfs-volume}

  filer-vol:
    name: ${FILER_VOL_NAME:-seaweedfs-filer}
